export const SITE_URL = "https://loopingbinary.com";
export const SITE_NAME = "Looping Binary";

export const SITE_DESCRIPTION =
  "Looping Binary is a Douala software company that builds products, websites, and systems, and trains engineers on live work. Client work includes Pejah, Presto, Laji, and Strategix. Products include Intellex, Zela, Tech Shop, LB App, LB Auth, Internship, Junior Dev, and LB Vote.";

export const KEYWORDS: string[] = [
  "Looping Binary",
  "LoopingBinary",
  "loopingbinary.com",
  "software company Douala",
  "software company Cameroon",
  "tech company Douala",
  "tech company Cameroon",
  "web development Douala",
  "web development Cameroon",
  "product design Douala",
  "UI UX Douala",
  "brand website Cameroon",
  "custom software Cameroon",
  "SaaS Cameroon",
  "marketplace Cameroon",
  "mobile money checkout",
  "MTN Money",
  "Orange Money",
  "PayUnit",
  "XAF payments",
  "fintech Cameroon",
  "edtech Cameroon",
  "e-commerce Douala",
  "e-commerce Cameroon",
  "booking website Cameroon",
  "salon website",
  "beauty brand website",
  "Pejah",
  "Pejah Braiding",
  "Presto Cameroon",
  "Presto marketplace",
  "Laji",
  "Laji Pearl",
  "Strategix",
  "SGS Fans",
  "Intellex",
  "Intellex LMS",
  "Zela",
  "Zela marketplace",
  "Tech Shop Douala",
  "laptop shop Cameroon",
  "LB App",
  "LB Auth",
  "OAuth Cameroon",
  "passwordless login",
  "LB Vote",
  "voting platform Cameroon",
  "Junior Dev Cameroon",
  "Junior Dev tournament",
  "coding tournament Cameroon",
  "internship Douala",
  "software internship Cameroon",
  "learn to code Douala",
  "developer training Cameroon",
  "engineering school Cameroon",
  "company school loop",
  "We Build We Grow We Train",
  "Looping Binary internship",
  "Looping Binary products",
  "African software studio",
  "African product company",
  "Douala startup",
  "Cameroon startup",
  "Central Africa software",
  "bilingual software English French",
  "développement web Douala",
  "entreprise tech Cameroun",
  "agence web Douala",
  "création site web Cameroun",
  "application web Cameroun",
  "formation développeur Douala",
  "stage informatique Douala",
  "Next.js agency",
  "React development Cameroon",
  "Node.js Cameroon",
  "full stack Douala",
  "product engineering Africa",
  "digital products Cameroon",
  "live software portfolio",
  "case studies Looping Binary",
  "hire developers Douala",
  "outsource software Cameroon",
  "build a website Douala",
  "build an app Cameroon",
  "school management software",
  "LMS Cameroon",
  "online learning Cameroon",
  "merchant dashboard",
  "marketplace for services Cameroon",
  "bus tickets app Cameroon",
  "fan voting Cameroon",
  "WhatsApp business Douala",
  "Tatoh Modest Wilton",
  "Looping Binary founder",
  "Douala Cameroon",
  "Littoral Cameroon tech",
  "Yaoundé delivery",
  "Arlington braiding website",
  "DFW salon website",
  "protective styles booking",
  "identity layer OAuth",
  "LBC coin",
  "shared auth SSO",
  "software that ships",
  "tested engineers",
  "live work training",
  "hire Looping Binary",
  "start a project Douala",
];
