export const SITE_URL = "https://loopingbinary.com";
export const SITE_NAME = "Looping Binary";

export const SITE_DESCRIPTION =
  "Looping Binary is a Douala, Cameroon technology company that builds software, mobile apps, and EdTech platforms, grows businesses, trains developers, and operates products like Intellex, Zela, Tech Shop, and Junior Dev. Founded by Tatoh Modest Wilton. We Build. We Grow. We Train.";

export const KEYWORDS: string[] = [
  "Looping Binary",
  "LoopingBinary",
  "loopingbinary.com",
  "Looping Binary Douala",
  "Looping Binary Cameroon",
  "Looping Binary Africa",
  "software company Douala",
  "software company Cameroon",
  "software company Africa",
  "tech company Douala",
  "tech company Cameroon",
  "tech company Africa",
  "best software company Cameroon",
  "best tech company Douala",
  "web development Douala",
  "web development Cameroon",
  "web development Africa",
  "mobile app development Cameroon",
  "mobile app development Douala",
  "product design Douala",
  "UI UX Douala",
  "brand website Cameroon",
  "custom software Cameroon",
  "custom software Africa",
  "SaaS Cameroon",
  "SaaS Africa",
  "marketplace Cameroon",
  "hire developers Douala",
  "hire software developers Cameroon",
  "outsource software Cameroon",
  "digital agency Douala",
  "digital agency Cameroon",
  "mobile money checkout",
  "MTN Money",
  "Orange Money",
  "PayUnit",
  "XAF payments",
  "fintech Cameroon",
  "edtech Cameroon",
  "edtech Africa",
  "e-commerce Douala",
  "e-commerce Cameroon",
  "booking website Cameroon",
  "salon website",
  "beauty brand website",
  "Pejah",
  "Pejah Braiding",
  "Presto Cameroon",
  "Presto marketplace",
  "Laji",
  "Laji Pearl",
  "Strategix",
  "SGS Fans",
  "Intellex",
  "Intellex LMS",
  "Intellex Looping Binary",
  "Zela",
  "Zela marketplace",
  "Tech Shop Douala",
  "laptop shop Cameroon",
  "LB App",
  "LB Auth",
  "OAuth Cameroon",
  "passwordless login",
  "LB Vote",
  "voting platform Cameroon",
  "Junior Dev Cameroon",
  "Junior Dev tournament",
  "Looping Binary Junior Dev",
  "coding tournament Cameroon",
  "internship Douala",
  "software internship Cameroon",
  "learn to code Douala",
  "developer training Cameroon",
  "developer training Africa",
  "coding bootcamp Cameroon",
  "engineering school Cameroon",
  "company school loop",
  "We Build We Grow We Train",
  "Looping Binary internship",
  "Looping Binary products",
  "Looping Binary solutions",
  "African software studio",
  "African product company",
  "African technology ecosystem",
  "Douala startup",
  "Cameroon startup",
  "Central Africa software",
  "bilingual software English French",
  "développement web Douala",
  "entreprise tech Cameroun",
  "agence web Douala",
  "création site web Cameroun",
  "application web Cameroun",
  "formation développeur Douala",
  "stage informatique Douala",
  "meilleure entreprise tech Douala",
  "Next.js agency",
  "React development Cameroon",
  "Node.js Cameroon",
  "full stack Douala",
  "product engineering Africa",
  "digital products Cameroon",
  "live software portfolio",
  "case studies Looping Binary",
  "build a website Douala",
  "build an app Cameroon",
  "school management software",
  "LMS Cameroon",
  "online learning Cameroon",
  "merchant dashboard",
  "marketplace for services Cameroon",
  "bus tickets app Cameroon",
  "fan voting Cameroon",
  "WhatsApp business Douala",
  "Tatoh Modest Wilton",
  "Modest Wilton",
  "Tatoh Modest",
  "Looping Binary founder",
  "CEO Looping Binary",
  "Douala Cameroon",
  "Littoral Cameroon tech",
  "Yaoundé delivery",
  "Arlington braiding website",
  "DFW salon website",
  "protective styles booking",
  "identity layer OAuth",
  "LBC coin",
  "shared auth SSO",
  "software that ships",
  "tested engineers",
  "live work training",
  "hire Looping Binary",
  "start a project Douala",
  "software development Africa",
  "digital transformation Cameroon",
  "digital transformation Douala",
];
